DROP DATABASE IF EXISTS FinalExam;
CREATE DATABASE FinalExam;
USE FinalExam;
CREATE TABLE GiangVien(
magv			TINYINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
hoten			NVARCHAR(20) NOT NULL,
luong			SMALLINT UNSIGNED
);
CREATE TABLE SinhVien(
masv			SMALLINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
hoten			NVARCHAR(20) NOT NULL,
namsinh			YEAR NOT NULL,
quequan			NVARCHAR(50)
);
CREATE TABLE DeTai(
madt			TINYINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
tendt			NVARCHAR(20) NOT NULL,
kinhphi			SMALLINT UNSIGNED,
NoiThucTap			NVARCHAR(50)
);
CREATE TABLE HuongDan(
id				TINYINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
masv			SMALLINT UNSIGNED,
madt			TINYINT UNSIGNED,
magv			TINYINT UNSIGNED,
ketqua			TINYINT UNSIGNED,
CONSTRAINT FK_sv FOREIGN KEY (masv) REFERENCES SinhVien(masv),
CONSTRAINT FK_dt FOREIGN KEY (madt) REFERENCES DeTai(madt),
CONSTRAINT FK_gv FOREIGN KEY (magv) REFERENCES GiangVien(magv)
);